### PR TITLE
Fix promise chain in count-sample

### LINKED ISSUE #94: Race condition in child-count sample
### How to reproduce these conditions

**Sample name or URL where you found the bug**
https://github.com/firebase/functions-samples/blob/master/child-count/functions/index.js#L42

**Failing Function code used (including require/import commands at the top)**
Using the sample code as is.

**Steps to set up and reproduce**
Using the sample code as is.

**Sample data pasted or attached as JSON (not an image)**
not needed

**Security rules used**
not needed

### Debug output
n/a

**Screenshots**
not needed

### Expected behavior
n/a

### Actual behavior
See my answer here: http://stackoverflow.com/a/43102002/394010

You are returning the once() function, not a promise chain.

Essentially, we've written this:

```
//returns the once promise
return ref.once('value', function(snap) { 
  /* some stuff that doesn't affect the promise chain happens here */
});
```

When what we wanted is this:

```
// returns whatever happens in the .then() callback
return ref.once('value').then(snap => {
   /* now whatever you return here affects the promise chain */
});
```

### PR DESCRIPTION
**Pull request by katowulf**
Fixes #94

### CODE REVIEW

File: child-count/functions/index.js [hunk 1]
```diff
@@ -39,7 +39,7 @@ exports.recountlikes = functions.database.ref("/posts/{postid}/likes_count").onW
   if (!event.data.exists()) {
     var counterRef = event.data.ref;
     var collectionRef = counterRef.parent.child('likes');
-    return collectionRef.once('value', function(messagesData) {
+    return collectionRef.once('value').then(function(messagesData) {
```
Comment (CodingDoug) [inline child-count/functions/index.js]: More idiomatic for ES6:
.then(messagesData => {

File: child-count/functions/index.js [hunk 2]
```diff
@@ -35,11 +35,11 @@ exports.countlikechange = functions.database.ref("/posts/{postid}/likes/{likeid}
 });
 
 // If the number of likes gets deleted, recount the number of likes
-exports.recountlikes = functions.database.ref("/posts/{postid}/likes_count").onWrite((event) => {
+exports.recountlikes = functions.database.ref('/posts/{postid}/likes_count').onWrite((event) => {
```
Comment (nicolasgarnier) [inline child-count/functions/index.js]: Remove parenthesis arround `event`
(Same above)

**Comment by puf** [comment]
Ouch. Good catch!
